cache:
  directories:
    - $HOME/download
    - $HOME/.cache/pip

language: generic

env:
    global:
        - TWINE_USERNAME=duguyue100

matrix:
    include:
        - os: linux
          sudo: required
          env: TOXENV=py27
        - os: linux
          sudo: required
          env: TOXENV=py34
        - os: linux
          sudo: required
          env: TOXENV=py35
        - os: linux
          sudo: required
          env: TOXENV=py36
        - os: linux
          sudo: required
          env: TOXENV=py37
        - os: osx
          sudo: required
          env:
              - TOXENV=py27
              - HOMEBREW_NO_AUTO_UPDATE=1
        - os: osx
          sudo: required
          env:
              - TOXENV=py34
              - HOMEBREW_NO_AUTO_UPDATE=1
        - os: osx
          sudo: required
          env:
              - TOXENV=py35
              - HOMEBREW_NO_AUTO_UPDATE=1
        - os: osx
          sudo: required
          env:
              - TOXENV=py36
              - HOMEBREW_NO_AUTO_UPDATE=1
        - os: osx
          sudo: required
          env:
              - TOXENV=py37
              - HOMEBREW_NO_AUTO_UPDATE=1



deploy:
  provider: releases
  api_key: $GITHUB_TOKEN 
  file_glob: true
  file: dist/*.whl
  skip_cleanup: true
  on:
    tags: true

before_install:
    - mkdir -p download
    - cd download
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
            wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
        else
            wget https://repo.continuum.io/miniconda/Miniconda2-latest-MacOSX-x86_64.sh -O miniconda.sh;
      fi 
    - chmod +x miniconda.sh
    - ./miniconda.sh -b -p $HOME/miniconda
    - cd ..
    - export PATH=$HOME/miniconda/bin:$PATH
    - conda info -a
    - conda update --yes conda
    - if [[ "$TOXENV" == "py34" ]]; then
        conda create -n py34 python=3.4 --yes;
        source activate py34;
      fi
    - if [[ "$TOXENV" == "py35" ]]; then
        conda create -n py35 python=3.5 --yes;
        source activate py35;
      fi
    - if [[ "$TOXENV" == "py36" ]]; then
        conda create -n py36 python=3.6 --yes;
        source activate py36;
      fi
    - if [[ "$TOXENV" == "py37" ]]; then
        conda create -n py37 python=3.7 --yes;
        source activate py37;
      fi
    - python --version
    - pip install pip -U
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        sudo apt-add-repository -y "ppa:ubuntu-toolchain-r/test";
        sudo apt-get -qq update;
        sudo apt-get -yq --no-install-suggests --no-install-recommends --force-yes install gcc-5 g++-5;
        sudo unlink /usr/bin/gcc && sudo ln -s /usr/bin/gcc-5 /usr/bin/gcc;
        sudo unlink /usr/bin/g++ && sudo ln -s /usr/bin/g++-5 /usr/bin/g++;
        gcc --version;
      fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        sudo apt-get install build-essential -y;
        sudo apt-get install libusb-1.0-0-dev -y;
        sudo apt-get install automake -y;
        sudo apt-get install bison -y;
      else
        brew install libusb;
        brew install automake;
        brew install bison;
      fi
    - git clone git://sigrok.org/libserialport
    - cd libserialport
    - ./autogen.sh
    - ./configure
    - make -j4
    - sudo make install
    - cd ..
    - $HOME/build/duguyue100/pyaer/install-libcaer.sh ci
    - git clone https://github.com/duguyue100/swig
    - cd swig
    - ./autogen.sh
    - ./configure --without-alllang --with-python=$(command -v python)
    - make
    - sudo make install
    - cd ..

install:
    - pip install numpy==1.16.1
    - pip install future -U
    - pip install wheel
    - if [[ $TRAVIS_TAG ]]; then
        pip install twine;
      fi
    - conda list

script:
    - make build-wheel
    - make build-wheel
    - make install
    - cd $HOME
    - python -c 'import pyaer; print(dir(pyaer))'
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        cd dist;
        for file in *.whl ; do mv $file ${file//linux/manylinux1} ; done;
        cd ..; 
      fi
    - if [[ $TRAVIS_TAG ]]; then
        twine upload -u ${TWINE_USERNAME} -p ${TWINE_PASSWORD} dist/*.whl;
      fi

branches:
  except:
    - refactor-compiling

notifications:
  email: false
