environment:
    matrix:
        - compiler: msys2
          ARCH: x64
          PYTHON_VERSION: "2.7"
          PYTHON: python3
          MSYS2_ARCH: x86_64
          MSYS2_DIR: msys64
          MSYSTEM: MINGW64
          MINICONDA: Miniconda-x64
        - compiler: msys2
          ARCH: x64
          PYTHON_VERSION: "3.6"
          PYTHON: python3
          MSYS2_ARCH: x86_64
          MSYS2_DIR: msys64
          MSYSTEM: MINGW64
          MINICONDA: Miniconda-x64

platform:
    - x64

matrix:
    fast_finish: true

install:
    - set PATH=C:\%MINICONDA%\Scripts;%PATH%
    - cd C:\%MSYS2_DIR%\home
    - git clone https://github.com/inilabs/libcaer
    - git clone https://github.com/duguyue100/swig
    - conda config --set always_yes yes --set changeps1 no
    - conda update --yes conda
    - conda create -q --name python%PYTHON_VERSION% python=%PYTHON_VERSION%
    - activate python%PYTHON_VERSION%
    - pip install numpy -U
    - conda list
    - C:\%MSYS2_DIR%\usr\bin\pacman --noconfirm --noprogressbar -Syu
    - C:\%MSYS2_DIR%\usr\bin\pacman --noconfirm --noprogressbar -Su
    - C:\%MSYS2_DIR%\usr\bin\pacman --noconfirm -S mingw-w64-x86_64-gcc
    - C:\%MSYS2_DIR%\usr\bin\pacman --noconfirm -S make mingw-w64-x86_64-cmake
    - C:\%MSYS2_DIR%\usr\bin\pacman --noconfirm -S mingw-w64-x86_64-pkg-config
    - C:\%MSYS2_DIR%\usr\bin\pacman --noconfirm -S mingw-w64-x86_64-libusb
    - C:\%MSYS2_DIR%\usr\bin\pacman --noconfirm -S automake bison
    - C:\%MSYS2_DIR%\usr\bin\bash -lc "cd /home/libcaer && cmake -G "MSYS Makefiles" -DCMAKE_INSTALL_PREFIX=/mingw64 ."
    - C:\%MSYS2_DIR%\usr\bin\bash -lc "cd /home/libcaer && make && make install"
    - C:\%MSYS2_DIR%\usr\bin\bash -lc "cd /home/swig && ./autogen.sh && ./configure --with-python=$(command -v python) --without-%PYTHON% && make && make install"

build: off
