"Hub":
    "use_default": true

"Subscriber-frame":
    "use_default": true
    "url": "tcp://127.0.0.1"
    "port": 5099
    "name": "frame-subscriber"
    "topic": ""
    "use_default_sub": false
    "custom_sub": "./custom_comm.py"
    "custom_class": "CustomSubscriber"
    "custom_1": 1234
    "custom_2": "something else"
    "custom_3": true

"Publisher-davis":
    "use_default": true 
    "url": "tcp://127.0.0.1"
    "port": 5100
    "master_topic": "davis_1"
    "name": "davis_publisher"
    "device": "DAVIS"
    "noise_filter": true
    "use_default_pub": false
    "bias_file": "../configs/davis346_config.json"
    "custom_pub": "./custom_comm.py"
    "custom_class": "CustomPublisher"
    "custom_1": 123
    "custom_2": "something"
    "custom_3": false
